add case

diff --git a/bin/sys_info_page b/bin/sys_info_page
--- a/bin/sys_info_page
+++ b/bin/sys_info_page
@@ -10,30 +10,28 @@ while true; do
 	cat <<- _EOF_ 
 		Please Select:
 	
-		1.Display System Information
-		2.Display Disk Space
-		3.Display Home Space Utilization
-		0.Quit
+		A.Display System Information
+		B.Display Disk Space
+		C.Display Home Space Utilization
+		Q.Quit
 	_EOF_
-	read -p "Enter selection [0-3] > "
+	read -p "Enter selection [A,B,C or Q] > "
 
-	if [[ $REPLY =~ ^[0-3]$ ]]; then
-		if [[ $REPLY == 0 ]]; then
-			break
-		fi
-		if [[ $REPLY == 1 ]]; then
-			echo "Hostname: $HOSTNAME"
+	case $REPLY in
+		q|Q)	echo "Program terminated."
+			exit
+			;;
+		a|A)	echo "Hostname: $HOSTNAME"
 			uptime
 			sleep $DELAY
 			continue
-		fi
-		if [[ $REPLY == 2 ]]; then
-			df -h
+			;;
+		
+		b|B)	df -h
 			sleep $DELAY
 			continue
-		fi
-		if [[ $REPLY == 3 ]]; then
-			if [[ $(id -u) -eq 0 ]]; then
+			;;
+		c|C)	if [[ $(id -u) -eq 0 ]]; then
 				echo "Home Space Utilization (All Users)"
 				du -sh /home/*
 			else
@@ -42,14 +40,12 @@ while true; do
 			fi
 			sleep $DELAY
 			continue
-		fi
-	else
-		echo "Invalid entry." >&2
-		sleep $DELAY
-	fi
+			;;
+		*)	echo "Invalid entry." >&2
+			exit 1
+			;;
+	esac
 done
-echo "Program terminated."
-
 TITLE="System Information Reprot For $HOSTNAME"
 CURRENT_TIME=$(date +"%x &r &z")
 TIME_STAMP="Generated $CURRENT_TIME,by $USER"
