add while

diff --git a/bin/sys_info_page b/bin/sys_info_page
--- a/bin/sys_info_page
+++ b/bin/sys_info_page
@@ -2,46 +2,53 @@
 
 #read-menu:a menu driven system information program
 
-clear
-echo "
-Please Select:
+DELAY=3
 
-1.Display System Information
-2.Display Disk Space
-3.Display Home Space Utilization
-0.Quit
-"
-read -p "Enter selection [0-3] > "
+while true; do
 
-if [[ $REPLY =~ ^[0-3]$ ]];then
-	if [[ $REPLY == 0 ]]; then
-		echo "Pragram terminated."
-		exit
-	fi
-	if [[ $REPLY == 1 ]]; then
-		echo "Hostname: $HOSTNAME"
-		uptime
-		exit
-	fi
-	if [[ $REPLY == 2 ]]; then
-		df -h
-		exit
-	fi
-	if [[ $REPLY == 3 ]]; then
-		if [[ $(id -u) -eq 0 ]]; then
-			echo "Home Space Utilization (All Users)"
-			du -sh /home/*
-		else
-			echo "Home Space Utilization ($USER)"
-			du -sh $HOME
+	clear
+	cat <<- _EOF_ 
+		Please Select:
+	
+		1.Display System Information
+		2.Display Disk Space
+		3.Display Home Space Utilization
+		0.Quit
+	_EOF_
+	read -p "Enter selection [0-3] > "
+
+	if [[ $REPLY =~ ^[0-3]$ ]]; then
+		if [[ $REPLY == 0 ]]; then
+			break
 		fi
-		exit
+		if [[ $REPLY == 1 ]]; then
+			echo "Hostname: $HOSTNAME"
+			uptime
+			sleep $DELAY
+			continue
+		fi
+		if [[ $REPLY == 2 ]]; then
+			df -h
+			sleep $DELAY
+			continue
+		fi
+		if [[ $REPLY == 3 ]]; then
+			if [[ $(id -u) -eq 0 ]]; then
+				echo "Home Space Utilization (All Users)"
+				du -sh /home/*
+			else
+				echo "Home Space Utilization ($USER)"
+				du -sh $HOME
+			fi
+			sleep $DELAY
+			continue
+		fi
+	else
+		echo "Invalid entry." >&2
+		sleep $DELAY
 	fi
-else
-	echo "Invalid entry." >&2
-	exit 1
-fi
-
+done
+echo "Program terminated."
 
 TITLE="System Information Reprot For $HOSTNAME"
 CURRENT_TIME=$(date +"%x &r &z")
