add io

diff --git a/bin/sys_info_page b/bin/sys_info_page
--- a/bin/sys_info_page
+++ b/bin/sys_info_page
@@ -1,4 +1,48 @@
 #!/bin/bash
+
+#read-menu:a menu driven system information program
+
+clear
+echo "
+Please Select:
+
+1.Display System Information
+2.Display Disk Space
+3.Display Home Space Utilization
+0.Quit
+"
+read -p "Enter selection [0-3] > "
+
+if [[ $REPLY =~ ^[0-3]$ ]];then
+	if [[ $REPLY == 0 ]]; then
+		echo "Pragram terminated."
+		exit
+	fi
+	if [[ $REPLY == 1 ]]; then
+		echo "Hostname: $HOSTNAME"
+		uptime
+		exit
+	fi
+	if [[ $REPLY == 2 ]]; then
+		df -h
+		exit
+	fi
+	if [[ $REPLY == 3 ]]; then
+		if [[ $(id -u) -eq 0 ]]; then
+			echo "Home Space Utilization (All Users)"
+			du -sh /home/*
+		else
+			echo "Home Space Utilization ($USER)"
+			du -sh $HOME
+		fi
+		exit
+	fi
+else
+	echo "Invalid entry." >&2
+	exit 1
+fi
+
+
 TITLE="System Information Reprot For $HOSTNAME"
 CURRENT_TIME=$(date +"%x &r &z")
 TIME_STAMP="Generated $CURRENT_TIME,by $USER"
@@ -19,7 +63,7 @@ report_disk_space () {
 }
 
 report_home_space () {
-	if [[ $(id -u) -eq 0 ]];then
+	if [[ $(id -u) -eq 0 ]]; then
 		cat <<- _EOF_
 			<H2>Home Space Utilization (All Users)</H2>
 			<PRE>$(du -sh /home/*)</PRE>
